In [18]:
import numpy as np

a = np.array([[3,4,5],[5,6,7],[6,7,8],[1,2,3]])
b = np.array([[1,2,3],[12,32,12]])
c = np.array([[1,2,23],[12,4,12]])
l = []
l.append(a)
l.append(b)
l.append(c)

l = np.array(l)
print(l)

[array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8],
       [1, 2, 3]])
 array([[ 1,  2,  3],
       [12, 32, 12]])
 array([[ 1,  2, 23],
       [12,  4, 12]])]


In [19]:
indices = [1,2]
res = np.take(l, indices)
l = np.delete(l, indices)

#print("res",res)
print("l",l)

l [array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8],
       [1, 2, 3]])]


In [20]:
fruits = ['banana', 'apple', 'cherry']
sample = 'apple'

indices = np.where(fruits == sample)
print(indices)

(array([], dtype=int64),)


In [22]:
8020//11

729

In [23]:
11*729

8019

In [24]:
data = np.ones((15,4))
print(data)
print(data.shape)

new = np.pad(data, [(0,5),(0,0)], 'constant', constant_values=0)

print(new)
print(new.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(15, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(20, 4)


In [28]:
10//6

1

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = [[1,2,3],[4,5,6],[7,8,9]]
c = [[1,2,3],[4,5,6],[7,8,9]]
d = [[1,2,3],[4,5,6],[7,8,9]]
print(a.shape)
val = [a,b,c,d]

res = np.stack(val)
print(res.shape)
print(res)

(3, 3)
(4, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [47]:
for x in res:
    sub = np.split(x,3)
    print(sub)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [45]:
a = ['a','b','c']
b = ['adsf','bsdf','csdf']

for s,l in zip(a,b):
    print("s:",s)
    print("l:",l)

s: a
l: adsf
s: b
l: bsdf
s: c
l: csdf
