In [10]:
import numpy as np

#np.random.seed(42)
indices = np.random.randint(0, 6384, 10)
print(indices)

[5611 2433 5311 5051 1184 4555 3385 4117 4843 2904]


In [19]:
indices = [1,2]
res = np.take(l, indices)
l = np.delete(l, indices)

#print("res",res)
print("l",l)

l [array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8],
       [1, 2, 3]])]


In [20]:
fruits = ['banana', 'apple', 'cherry']
sample = 'apple'

indices = np.where(fruits == sample)
print(indices)

(array([], dtype=int64),)


In [22]:
8020//11

729

In [23]:
11*729

8019

In [24]:
data = np.ones((15,4))
print(data)
print(data.shape)

new = np.pad(data, [(0,5),(0,0)], 'constant', constant_values=0)

print(new)
print(new.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(15, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(20, 4)


In [28]:
10//6

1

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = [[1,2,3],[4,5,6],[7,8,9]]
c = [[1,2,3],[4,5,6],[7,8,9]]
d = [[1,2,3],[4,5,6],[7,8,9]]
print(a.shape)
val = [a,b,c,d]

res = np.stack(val)
print(res.shape)
print(res)

(3, 3)
(4, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [47]:
for x in res:
    sub = np.split(x,3)
    print(sub)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [45]:
a = ['a','b','c']
b = ['adsf','bsdf','csdf']

for s,l in zip(a,b):
    print("s:",s)
    print("l:",l)

s: a
l: adsf
s: b
l: bsdf
s: c
l: csdf


In [55]:
print(np.array([10,44,2]).argsort()) # argsort liefert die permutation der indices die das array aufsteigend sortiert

[2 0 1]


In [59]:
a = np.array([[3,4,0],
              [1,2,6],
              [6,5,7]])

c = np.array([[11., 34., 56.],
              [10.,  8., 12.],
              [ 5.,  4.,  6.]])
wasichwill = np.array([[56, 11, 34],
                       [12, 10, 8],
                       [6, 5, 4]])
b = c[:,-c[1,:].argsort()]
print(b)

[[56. 11. 34.]
 [12. 10.  8.]
 [ 6.  5.  4.]]


In [63]:
one = ['a','b','c']
two = ['d','e','f']

print(np.concatenate((one, two)))

['a' 'b' 'c' 'd' 'e' 'f']


In [65]:
import csv
with open("output.csv", "w", newline='') as f:
            writer = csv.writer(f)
            writer.writerow([123.4,454.3,123.334,234.455,8])

In [73]:
import pandas as pd

data = pd.read_csv("fakefeatures.csv").values
print(np.mean(data[:,0:98],axis=0).shape)
data[:,0:98] = (data[:,0:98]-np.mean(data[:,0:98],axis=0))/np.std(data[:,0:98],axis=0)
data = pd.DataFrame(data)
data.to_csv("normalizedfeatures.csv")

(98,)


In [77]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [11,1,2]])
print(a.shape)
b = np.take(a,[1,2], axis=0)
a=np.delete(a,[1,2], axis=0)

print(a)
print("b")
print(b)

(4, 3)
[[ 1  2  3]
 [11  1  2]]
b
[[4 5 6]
 [7 8 9]]


In [80]:
from scipy import ndimage
a = np.array([3,4,7,5,9,3,3,4,3,5,9,24])
res = ndimage.sobel(a, 0)
print(res)

[ 1  4  1  2 -2 -6  1  0  1  6 19 15]


In [85]:
results = np.array([[350, 700, 1500],[100, 560, 400],[234,456,234]])
print(results)
print((-results[1,:]).argsort())
results = results[:,-results[1,:].argsort()]
print(results)

[[ 350  700 1500]
 [ 100  560  400]
 [ 234  456  234]]
[1 2 0]
[[ 350  700 1500]
 [ 100  560  400]
 [ 234  456  234]]


In [103]:
# experimenting with threaded feature extraction
from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
import itertools
import sys
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from scipy import signal
from scipy import ndimage
import csv

sensors = ['EMG1', 'EMG2', 'EMG3', 'EMG4', 'Microphone', 'ACC upper X', 'ACC upper Y','ACC upper Z', 'Goniometer X',
          'ACC lower X', 'ACC lower Y', 'ACC lower Z', 'Goniometer Y', 'Gyro upper X', 'Gyro upper Y', 'Gyro upper Z',
          'Gyro lower X', 'Gyro lower Y', 'Gyro lower Z']

variance_sensors = ['EMG1', 'EMG2', 'EMG3', 'EMG4', 'Microphone']

smooth_sensors = ['ACC upper X', 'ACC upper Y','ACC upper Z', 'Goniometer X','ACC lower X', 'ACC lower Y', 
                  'ACC lower Z', 'Goniometer Y', 'Gyro upper X', 'Gyro upper Y', 'Gyro upper Z', 'Gyro lower X', 
                  'Gyro lower Y', 'Gyro lower Z']

def smooth(data, windowsize, std):
    kernel = signal.gaussian(windowsize, std=std)
    kernel /= np.sum(kernel)
    return np.convolve(data, kernel, 'valid')

def variance_filter(data, windowsize):
    half = windowsize//2
    res = np.zeros(data.shape[0]-windowsize)
    for i in range(half,len(data)-half):
        res[i-half] = np.std(data[i-half:i+half])
    return res / np.max(res)

def sample(data, num_samples):
    samples = [int(sample) for sample in np.linspace(0, data.shape[0]-1, num_samples)]
    return data[samples]
    
def smooth_extractor(data, num_samples):
    """
    data = 1d-numpy array of length timestep:
    """
    smoothed = smooth(data,200,50)
    normalized = (smoothed-np.mean(smoothed))/np.max(smoothed)
    return sample(normalized, num_samples)

def variance_extractor(data, num_samples):
    """
    data = 1d-numpy array of length timesteps
    """
    var_data = smooth(variance_filter(data,windowsize=100),windowsize=100,std=25)
    return sample(var_data, num_samples)

def threaded_recurrent_feature_extractor(data, num_samples):
    """
    data = 2d-numpy array of shape [timesteps, sensors]
    
    """
    pool = ThreadPool(4)
    
    variance_sequences = []
    smooth_sequences = []
    
    for sensor in variance_sensors:
        variance_sequences.append(data[:,sensors.index(sensor)])
        
    for sensor in smooth_sensors:
        smooth_sequences.append(data[:,sensors.index(sensor)])
        
    var_results = pool.starmap(variance_extractor, zip(variance_sequences, itertools.repeat(num_samples)))
    smo_results = pool.starmap(smooth_extractor, zip(smooth_sequences, itertools.repeat(num_samples)))
        
    pool.close()
    pool.join()
    
    return var_results + smo_results

def recurrent_feature_extractor(data, num_samples):
    """
    data = 2d-numpy array of shape [timesteps, sensors]
    
    """
    features = []
        
    for sensor in variance_sensors:
        features.append(variance_extractor(data[:,sensors.index(sensor)], num_samples))
        
    for sensor in smooth_sensors:
        features.append(smooth_extractor(data[:,sensors.index(sensor)], num_samples))
        
    return features

In [104]:
import pandas as pd
import timeit

path = "/Users/thomasklein/Projects/BremenBigDataChallenge2019/bbdc_2019_Bewegungsdaten/Subject02/Subject02_Aufnahme215.csv"
testdata = pd.read_csv(path).values

res = threaded_recurrent_feature_extractor(testdata, 80)

import timeit

start_time = timeit.default_timer()
for i in range(1000):
    res = threaded_recurrent_feature_extractor(testdata, 80)
print("Threaded result:",timeit.default_timer() - start_time)

start_time = timeit.default_timer()
for i in range(1000):
    res = threaded_recurrent_feature_extractor(testdata, 80)
print("Unthreaded result:",timeit.default_timer() - start_time)

Threaded result: 356.95526433794294
Unthreaded result: 356.7150718709454


In [ ]:
import tensorflow as tf

new_model = tf.keras.models.load_model('/Users/thomasklein/Projects/BremenBigDataChallenge2019/bigdatachallenge/recurrent/model/readout_lstm.h5')
new_model.summary()

In [107]:
import numpy as np

np.random.seed(42)
indices = np.random.randint(0, 6384, 10)
print(indices)

In [33]:
a = np.array([[1,2,3,4],
            [4,5,6,7],
            [8,3,6,7]])

b = np.array([3,4,5])

(a.T * b).T

array([[ 3,  6,  9, 12],
       [16, 20, 24, 28],
       [40, 15, 30, 35]])

In [36]:
import tensorflow as tf

tf.enable_eager_execution()

vals = tf.constant([[4.0, 5.4, 6.9, 7.0,],
                    [4.5, 1.2, 3.1, 7.9],
                    [5.7, 3.1, 7.8, 8.7]], dtype=tf.float32) # shape (3,4)
means = tf.constant([1,2,3,4], dtype=tf.float32)


print(vals-means)

ValueError: tf.enable_eager_execution must be called at program startup.